### ISSUE TITLE
Can't get site name when you switch root page

### ISSUE THREAD

**Issue by besarbertasholli** [coderedcorp/wagtail-seo#32]
Wagtail SEO library model throws error AttributeError: 'NoneType' object has no attribute 'site_name'
Error on method:
def seo_sitename(self) -> str:
return self.get_site().site_name

I have created two pages under the Root page of Wagtail. One is the "Under construction" page, and the other is the homepage. The homepage has children pages under it. The configured root page for the site is the "Under construction" page at the moment.  When we are trying to edit the homepage or its children as we get ready to deploy it, we are trying to use the preview function of wagtail. The preview mode throws the error mentioned above from the method seo_sitename def seo_sitename(self) -> str: as get site returns None and then return self.get_site().site_name doesn't work.
I believe this is a bug as the library should still be able to get the real site name, even though I have some other root page configured. This may also be prevented in some other way, with try and except or some error handling solution.
I hope you can reproduce the same issue in an easy way, and try to fix it.
Thank you for understanding.

**Comment by vsalvino** [comment]
It sounds like the homepage does not belong to a site, so the error makes sense at least. Since "under construction" is your current root page, can you try moving HomePage underneath it?

Regardless, wagtail-seo should still handle the case where a page does not have a site, and return None/empty string instead of throwing an error. So assuming that pages have a site could be considered a bug and should be handled.

**Comment by vsalvino** [comment]
Fix for this is in 1.0.1 and 2.0.1.
