### ISSUE TITLE
This lib is nearly awesome, but what about keywords?

### ISSUE THREAD

**Issue by kakulukia** [coderedcorp/wagtail-seo#46]
I don't see why there is no field for entering keywords per page.
How come?

**Comment by vsalvino** [comment]
Keywords (the `<meta>` tag) are explicitly ignored by search engines due to spammy sites abusing them in the early days of the web. Therefore we do not include them, as it would be misleading to editors who think the keywords are helping in some way. See: https://developers.google.com/search/docs/crawling-indexing/special-tags#unsupported

Virtually all SEO guidance published by Google etc. now uses the word "Keywords" to refer to important words that appear in your title tag and body content. So adding a keywords field would prove doubly confusing to editors.

A useful form of "Keywords" in this package would be to scan the page, and through heuristics, determine which keywords a search engine might find. This is similar to what Yoast does.

**Comment by kakulukia** [comment]
Very interesting, didnt know - some seo tools still complain about missing keywords on our site. Thanks for the heads up!
