### ISSUE TITLE
Wagtail 5 

### ISSUE THREAD

**Issue by drkoru** [coderedcorp/wagtail-seo#47]
Greetings. The package is marked not to support Wagtail 5. My dependencies failed during a wagtail upgrade to 5.0 so I had to remove the Seo features now. An update to support Wagtail 5 would be appreciated. thanks

**Comment by uplinkdgroup** [comment]
Is anything happening here or is this project dead?

**Comment by vsalvino** [comment]
Comments like "it needs an update" or "is it dead" are completely useless and a waste of everyone's time. Whenever a new major Wagtail release drops, we have an absolute mountain of software to update, literally hundreds of projects. This takes time. Please be patient, or contribute, or purchase support. Those are your options.

This is an open source project. It is stable, not dead. That means:
* You are welcome, and encouraged, to fork or make a pull request.
* If you are using this freely available software in a critical system, you should purchase a support contract to ensure your needs can be met. Otherwise as the license states it is provided without warranty.
* Wagtail 4.2 is perfectly stable, nobody is forcing you to use Wagtail 5. Yes, it is exciting when a new Wagtail release drops, but it requires a ton of work to add support all the way down the dependency chain. This is only one of many dependencies we have to support.

**Comment by uplinkdgroup** [comment]
Hi Vince, I sense you are frustrated with open source. 
As drkoru noted but was not replied to 'The package is marked **not to support Wagtail 5**'.

I'm not looking to get into it with you but since i've obviously triggered you:
1. The package you have created bottlenecks project upgrades. - This makes the question a reasonable one to ask. 
2. There have been no responses to comments for well over a month - Has it been abandoned? Who knows?
3. People are interested if there are any roadmap plans to upgrade it in the near term. To upgrade we need to spend our time removing it from our project -- Please advise?
4. Next time... Maybe be upfront in the future when releasing open-source packages (that have an upgrade bottleneck) to include premium paid purchase support plans in mind as your business model - Many might avoid this route.

Thanks for your time replying. Guess we'll take it the project is somewhat 'alive'

**Comment by viscas91** [comment]
@vsalvino Why should we use wagtail 4.2 ? I upgrade libraries work with latest versions to avoid any security issue, **wagtail-seo** is downgrading packages for both django and wagtail.

for everyone else who were using this package, you can use **wagtail-metadata** which is extension of django-meta for wagtail.

**Comment by uplinkdgroup** [comment]
@vsalvino Do you plan to support Wagtail 5? If so can you please provide an approximate ETA?

++ @viscas91 
++ @drkoru

**Comment by horza** [comment]
Any update on support for Wagtail 5?

**Comment by sebastian-muthwill** [comment]
The point @vsalvino is making is fully valid and understandable. This is how open source works. 

However there is already a PR #49 pending since mid September to bump the wagtail to 5.1. 
The checks have passed but it needs to be merged.
